<!DOCTYPE html>
<html lang="id" class="bg-[#f5f8fc]">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Dashboard BK Mardisiswa</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800&family=Plus+Jakarta+Sans:wght@600;700;800&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,400,0,0" rel="stylesheet">
    @vite(['resources/css/app.css', 'resources/js/app.js'])
</head>
<body class="dashboard-body">
<div class="app-shell">
    <aside class="sidebar" id="sidebar">
        <div class="brand"><div class="brand-mark"><span class="material-symbols-outlined">school</span></div><div><strong>BK Mardisiswa</strong><small>LAYANAN KONSELING</small></div></div>
        <div class="portal-chip"><span class="material-symbols-outlined">verified_user</span>Portal Bimbingan Terpadu</div>
        <nav class="nav-list" aria-label="Navigasi utama">
            <a class="nav-item active" href="{{ url('/dashboard') }}"><span class="material-symbols-outlined">dashboard</span>Dashboard</a>
            <a class="nav-item" href="{{ route('dashboard.module', 'students') }}"><span class="material-symbols-outlined">clinical_notes</span>Buku Induk Siswa</a>
            <a class="nav-item" href="{{ route('dashboard.module', 'violations') }}"><span class="material-symbols-outlined">assignment_late</span>Input Pelanggaran</a>
            <a class="nav-item" href="{{ route('dashboard.module', 'agenda') }}"><span class="material-symbols-outlined">event</span>Jadwal &amp; Home Visit</a>
            <a class="nav-item" href="{{ route('dashboard.module', 'assessments') }}"><span class="material-symbols-outlined">psychology</span>Asesmen &amp; Karir</a>
            <a class="nav-item" href="{{ route('dashboard.module', 'reports') }}"><span class="material-symbols-outlined">summarize</span>Rekap &amp; Laporan</a>
            <a class="nav-item" href="{{ route('dashboard.module', 'settings') }}"><span class="material-symbols-outlined">settings</span>Pengaturan</a>
        </nav>
        <div class="help-card"><span class="material-symbols-outlined">support_agent</span><strong>Bantuan Teknis</strong><p>Hubungi admin IT sekolah jika ada kendala data.</p></div>
    </aside>

    <main class="main-content">
        <header class="topbar"><button class="mobile-menu" data-menu-toggle aria-label="Buka menu"><span class="material-symbols-outlined">menu</span></button><div class="search-box"><span class="material-symbols-outlined">search</span><input aria-label="Cari siswa" placeholder="Cari siswa, NIS, kelas..." /></div><div class="top-actions"><div class="year-chip"><span class="material-symbols-outlined">school</span><span>TA 2024/2025<small>Ganjil</small></span></div><button class="case-button"><span class="material-symbols-outlined">add_circle</span>Catat Kasus</button><button class="icon-button" aria-label="Notifikasi"><span class="material-symbols-outlined">notifications</span><i></i></button><div class="profile"><div class="avatar">{{ collect(explode(' ', $currentUser->name))->map(fn ($part) => substr($part, 0, 1))->take(2)->implode('') }}</div><span><strong>{{ $currentUser->name }}</strong><small>Guru BK</small></span></div></div></header>

        <div class="page-wrap">
            <section class="welcome-banner"><div><span class="eyebrow"><span class="material-symbols-outlined">psychology</span>Layanan Bimbingan &amp; Konseling Terpadu</span><h1>Selamat Datang, {{ $currentUser->name }}</h1><p>Ringkasan aktivitas pendampingan, kedisiplinan, dan layanan<br class="desktop-only"> perkembangan siswa SMA Mardisiswa secara komprehensif hari ini.</p></div><div class="banner-actions"><a class="primary-action" href="{{ route('dashboard.module', 'agenda') }}"><span class="material-symbols-outlined">add_circle</span>+ Konseling Baru</a><a class="light-action" href="{{ route('dashboard.module', 'violations') }}"><span class="material-symbols-outlined">warning</span>+ Catat Pelanggaran Cepat</a><a class="soft-action" href="{{ route('dashboard.export.violations') }}"><span class="material-symbols-outlined">download</span>Ekspor Laporan</a></div><small class="banner-date">{{ now()->translatedFormat('l, d F Y') }}</small></section>

            <section class="metric-grid"><div class="metric-card"><div class="metric-heading"><span>TOTAL SISWA<br>AKTIF</span><span class="metric-icon lavender"><span class="material-symbols-outlined">groups</span></span></div><div class="metric-value">{{ $totalStudents }} <small>Siswa</small></div><div class="metric-foot"><span>{{ $classCount }} Rombel<br>X, XI, XII</span><b>Aktif<br>Terdaftar</b></div></div><div class="metric-card"><div class="metric-heading"><span>KASUS KONSELING<br>AKTIF</span><span class="metric-icon mint"><span class="material-symbols-outlined">chat</span></span></div><div class="metric-value teal">{{ $activeCases }} <small>Kasus Berjalan</small></div><div class="metric-foot"><span>{{ $completedThisWeek }} Selesai<br>Pekan Ini</span><b>Data<br>Aktif</b></div></div><div class="metric-card"><div class="metric-heading"><span>PELANGGARAN HARI<br>INI</span><span class="metric-icon rose"><span class="material-symbols-outlined">warning</span></span></div><div class="metric-value red">{{ $todayViolations }} <small>Siswa Tercatat</small></div><div class="metric-foot"><span class="red-text">{{ $todayLate }}<br>Keterlambatan</span><b>{{ max(0, $todayViolations - $todayLate) }}<br>Lainnya</b></div></div><div class="metric-card"><div class="metric-heading"><span>HOME VISIT &amp;<br>PANGGILAN</span><span class="metric-icon blue"><span class="material-symbols-outlined">location_on</span></span></div><div class="metric-value blue-text">{{ $scheduledActions }} <small>Tindakan</small></div><div class="metric-foot"><span>Terjadwal<br>Aktif</span><b>Home Visit<br>&amp; Panggilan</b></div></div></section>

            <div class="content-grid"><div class="content-column"><section class="panel attendance-panel"><div class="panel-title"><div><h2><span class="material-symbols-outlined">insert_chart</span> Tren Kehadiran &amp; Kedisiplinan Siswa</h2><p>Analisis keterlambatan &amp; kehadiran kumulatif 4 pekan Oktober 2024</p></div><div class="period-toggle"><button class="selected">Bulan Ini</button><button>Semester 1</button></div></div><div class="attendance-summary"><div><small>RATA-RATA HADIR TEPAT WAKTU</small><strong>96.8% <em>↑ +0.4%</em></strong></div><div><small>TOTAL KETERLAMBATAN</small><strong class="dark">28 <em>Insiden</em></strong></div><div><small>TOTAL ALPHA / TANPA KET.</small><strong class="red-text">6 <em>Hari</em></strong></div></div><div class="legend"><span>Minggu Evaluasi</span><span><i class="dot teal-dot"></i>Tepat Waktu (&gt;95%)</span><span><i class="dot amber-dot"></i>Terlambat</span><span><i class="dot red-dot"></i>Alpha</span></div><div class="bars"><div><label>Pekan 1 (1 - 6 Okt)<b>97.2% Tepat Waktu | 8 Terlambat | 1 Alpha</b></label><div class="bar"><i style="width:93%"></i><b style="width:5%"></b><em style="width:2%"></em></div></div><div><label>Pekan 2 (7 - 13 Okt)<b>96.0% Tepat Waktu | 11 Terlambat | 3 Alpha</b></label><div class="bar"><i style="width:89%"></i><b style="width:7%"></b><em style="width:3%"></em></div></div><div><label>Pekan 3 (14 - 20 Okt)<b>98.1% Tepat Waktu | 5 Terlambat | 1 Alpha</b></label><div class="bar"><i style="width:95%"></i><b style="width:3%"></b><em style="width:2%"></em></div></div><div><label>Pekan 4 (21 - 24 Okt - Berjalan)<b>96.5% Tepat Waktu | 4 Terlambat | 1 Alpha</b></label><div class="bar"><i style="width:92%"></i><b style="width:5%"></b><em style="width:2%"></em></div></div></div><div class="class-summary"><span>Kelas X (Fase E) <b>98.2% Hadir</b></span><span>Kelas XI (Fase F) <b>96.4% Hadir</b></span><span>Kelas XII <b>95.8% Hadir</b></span></div></section>

<section class="panel attention-panel"><div class="panel-title"><div><h2><span class="material-symbols-outlined red-text">notifications_active</span> Perhatian Khusus Siswa</h2><p>Daftar siswa dengan akumulasi poin catatan perilaku mendekati ambang konseling intensif</p></div><a href="{{ route('dashboard.module', 'students') }}">Lihat Semua Siswa <span class="material-symbols-outlined">arrow_forward</span></a></div><div class="student-table"><div class="table-head"><span>NO</span><span>SISWA &amp; KELAS</span><span>AKUMULASI<br>POIN</span><span>FOKUS<br>CATATAN</span><span>STATUS<br>TINDAKAN</span><span></span></div>@foreach ($attentionStudents as $i => $student)<div class="table-row"><span>{{ $i + 1 }}</span><span class="student-name"><i class="initial initial-{{ $i % 5 }}">{{ collect(explode(' ', $student->name))->map(fn ($part) => substr($part, 0, 1))->take(2)->implode('') }}</i><span><strong>{{ $student->name }}</strong><small>NISN: {{ $student->nisn ?? $student->nis }} · {{ $student->schoolClass->name }}</small></span></span><span class="points p-{{ $i % 5 }}">{{ $student->discipline_points }}<small>Poin</small></span><span>{{ $student->violations->first()?->violationType?->name ?? 'Perlu pemantauan berkala' }}</span><span class="status status-{{ $i % 5 }}">{{ str_replace('_', ' ', ucfirst($student->discipline_status)) }}</span><button aria-label="Lihat siswa"><span class="material-symbols-outlined">person</span></button></div>@endforeach</div><div class="threshold"><span class="material-symbols-outlined">info</span>Ambang batas pemanggilan orang tua diatur pada akumulasi 75 poin pelanggaran.<a href="{{ route('dashboard.module', 'students') }}">Atur Regulasi<br>Poin</a></div></section></div>

<aside class="right-column"><section class="panel agenda-panel"><div class="side-title"><h2><span class="material-symbols-outlined">calendar_month</span> Agenda Terdekat <b>2 Agenda</b></h2></div><article class="agenda-item agenda-teal"><header><span>09:30 - 10:30 WIB<br>(Hari Ini)</span><b>Ruang<br>BK 1</b></header><strong>Rizky Aditya (XI IPS 1)</strong><p>Bimbingan Karir &amp; Minat Studi Lanjut PTN</p><footer>Konseling Individu <button><span class="material-symbols-outlined">play_arrow</span>Mulai Sesi</button></footer></article><article class="agenda-item agenda-red"><header><span>13:00 WIB (Siang Ini)</span><b>Ruang Rapat<br>BK</b></header><strong>Ortu Dimas Arya Pratama</strong><p>Konfirmasi Pemantauan Kehadiran &amp; Surat Peringatan</p><footer>Didampingi Wali Kelas <button>Buka Berkas</button></footer></article><article class="agenda-item agenda-blue"><header><span>Jumat, 25 Okt<br>14:00 WIB</span><b>Kunjungan<br>Rumah</b></header><strong>Ananda Sarah Melani (X-4)</strong><p>Pendampingan Adaptasi Lingkungan bersama Wali Kelas</p><footer>Kel. Bulusan, Tembalang <button>Peta &amp; Info</button></footer></article></section><section class="panel topic-panel"><div class="side-title"><h2><span class="material-symbols-outlined teal-text">donut_large</span> Distribusi Topik Masalah <small>Bulan Ini</small></h2></div><div class="topic-row"><label>Kedisiplinan &amp; Tata Tertib <b>45% (18 Kasus)</b></label><div><i style="width:45%"></i></div></div><div class="topic-row"><label>Masalah Belajar &amp; Akademik <b>28% (11 Kasus)</b></label><div><i style="width:28%"></i></div></div><div class="topic-row"><label>Bimbingan Karir &amp; Studi <b>20% (8 Kasus)</b></label><div><i style="width:20%"></i></div></div><div class="topic-row"><label>Sosial &amp; Pribadi (Personal) <b>7% (3 Kasus)</b></label><div><i style="width:7%"></i></div></div><footer class="topic-foot">Laporan Periodik<br>Otomatis <b>Unduh Analitik<br>BK <span class="material-symbols-outlined">download</span></b></footer></section><section class="reflection"><span class="material-symbols-outlined">lightbulb</span><small>REFLEKSI GURU PEMBIMBING</small><p>“Disiplin bukanlah tentang menghukum kesalahan, melainkan melatih nurani siswa agar bertumbuh menjadi pribadi yang bertanggung jawab atas setiap pilihannya.”</p></section></aside></div>
        </div>
    </main>
</div>
</body>
</html>
