@extends('layouts.dashboard')

@section('content')
@if($module === 'violations')
<div class="violation-page">
    @if(session('success'))<div class="alert-success"><span class="material-symbols-outlined">check_circle</span>{{ session('success') }}</div>@endif
    @if($errors->any())<div class="alert-error"><span class="material-symbols-outlined">error</span>{{ $errors->first() }}</div>@endif
    <div class="violation-page-head"><div><div class="student-breadcrumb"><a href="{{ route('dashboard') }}"><span class="material-symbols-outlined">home</span> Beranda</a><span>/</span><strong>Input Pelanggaran</strong></div><span class="eyebrow">SISTEM KEDISIPLINAN TERPADU · TA 2024/2025</span><h1>Input &amp; Pencatatan Pelanggaran Siswa</h1><p>Pencatatan kedisiplinan cepat dengan kalkulasi poin otomatis dan notifikasi instan ke wali kelas serta orang tua.</p></div><div class="quick-status"><span><i></i> Petugas: {{ auth()->user()->name }}</span><b><span class="material-symbols-outlined">schedule</span>{{ now()->format('d M Y, H:i') }} WIB</b></div></div>
    <form method="POST" action="{{ route('dashboard.violation.store') }}" enctype="multipart/form-data" class="violation-layout" data-violation-form>
        @csrf
        <div class="violation-form-column">
            <section class="violation-card"><div class="section-heading"><div><span class="step-number">01</span><h2>Identitas Siswa Terlapor</h2></div><small>Pencarian otomatis</small></div><div class="student-picker"><span class="material-symbols-outlined">person_search</span><select name="student_id" required data-student-select><option value="">Pilih nama atau NIS siswa...</option>@foreach($students as $student)<option value="{{ $student->id }}" data-points="{{ $student->discipline_points }}" data-class="{{ $student->schoolClass?->name }}">{{ $student->name }} — {{ $student->nis }} ({{ $student->schoolClass?->name ?? 'Tanpa kelas' }})</option>@endforeach</select><span class="material-symbols-outlined">expand_more</span></div><div class="selected-student" data-student-preview><span class="student-avatar">--</span><div><strong data-student-name>Belum memilih siswa</strong><small>NIS &amp; kelas akan tampil di sini</small></div><div class="student-points"><small>Poin berjalan</small><strong data-student-points>0</strong><span>/ 100</span></div></div></section>
            <section class="violation-card"><div class="section-heading"><div><span class="step-number">02</span><h2>Pilih Jenis Pelanggaran</h2></div><small>Buku Pedoman BK Mardisiswa</small></div><div class="category-tabs" data-category-tabs>@foreach($violationTypes->pluck('category')->unique() as $category)<button type="button" data-category="{{ $category }}">{{ ucwords(str_replace('_', ' & ', $category)) }}</button>@endforeach</div><div class="violation-options">@foreach($violationTypes as $type)<label class="violation-option" data-type-category="{{ $type->category }}"><input type="radio" name="violation_type_id" value="{{ $type->id }}" data-points="{{ $type->point_weight }}" required><span><strong>{{ $type->name }}</strong><small>{{ $type->description ?? 'Catatan kedisiplinan siswa sesuai pedoman sekolah.' }}</small></span><b>+{{ $type->point_weight }} Poin</b></label>@endforeach</div></section>
            <section class="violation-card"><div class="section-heading"><div><span class="step-number">03</span><h2>Kontekstual Kejadian</h2></div><small>Wajib diisi guru piket</small></div><div class="form-grid"><label>Waktu &amp; tanggal kejadian<input type="datetime-local" name="occurred_at" value="{{ old('occurred_at', now()->format('Y-m-d\\TH:i')) }}" required></label><label>Lokasi kejadian<select name="location"><option>Gerbang Depan Sekolah</option><option>Koridor Lantai 2</option><option>Kantin Belakang</option><option>Ruang Kelas</option><option>Lapangan Olahraga</option></select></label></div><label class="notes-field">Catatan guru piket &amp; alasan siswa<textarea name="notes" rows="4" placeholder="Tuliskan kronologi singkat kejadian...">{{ old('notes') }}</textarea></label><label class="upload-field"><span class="material-symbols-outlined">photo_camera</span><span><strong>Dokumentasi bukti (opsional)</strong><small>JPG, PNG maksimal 5MB</small></span><input type="file" name="evidence" accept="image/*"></label></section>
        </div>
        <aside class="violation-side-column"><section class="summary-card"><div class="section-heading"><div><span class="material-symbols-outlined">calculate</span><h2>Kalkulasi Otomatis Poin Siswa</h2></div><small>Real-time sync</small></div><div class="point-summary"><div><small>Poin Lama</small><strong data-old-points>0</strong></div><span>+</span><div><small>Pelanggaran Baru</small><strong data-new-points>0</strong></div><em>= <b data-total-points>0</b></em></div><div class="threshold"><div><span>Ambang batas peringatan BK</span><b data-threshold>0 / 100 Poin</b></div><i><b data-meter></b></i><small>0 Aman &nbsp;&nbsp; 50 SP 1 &nbsp;&nbsp; 75 SP 2 &nbsp;&nbsp; 100 Konferensi Kasus</small></div></section><section class="summary-card action-card"><div class="section-heading"><div><span class="material-symbols-outlined">notifications_active</span><h2>Otomasi Distribusi Notifikasi</h2></div></div><p>Sistem akan mengirim ringkasan data kedisiplinan setelah formulir disimpan.</p><label><input type="checkbox" name="notify_homeroom_teacher" value="1" checked><span class="material-symbols-outlined">school</span> WhatsApp ke Wali Kelas</label><label><input type="checkbox" name="notify_guardian" value="1" checked><span class="material-symbols-outlined">family_restroom</span> Notifikasi Orang Tua / Wali</label><button class="primary-action submit-violation" type="submit"><span class="material-symbols-outlined">save</span>Simpan &amp; Kirim Notifikasi</button><button class="reset-action" type="reset">Reset Formulir</button></section></aside>
    </form>
    <section class="violation-card recent-violations"><div class="section-heading"><div><span class="material-symbols-outlined">history</span><h2>Pencatatan Kedisiplinan Terakhir Hari Ini</h2></div><a href="{{ route('dashboard.export.violations') }}">Lihat laporan lengkap →</a></div><div class="recent-table"><div class="recent-row recent-head"><span>JAM</span><span>NAMA SISWA</span><span>JENIS PELANGGARAN</span><span>POIN</span><span>STATUS</span></div>@forelse($rows as $row)<div class="recent-row"><span>{{ $row->occurred_at?->format('H:i') }} WIB</span><strong>{{ $row->student?->name }}</strong><span>{{ $row->violationType?->name }}</span><b>+{{ $row->point_snapshot }}</b><em>{{ ucfirst($row->action_status) }}</em></div>@empty<div class="empty-state">Belum ada pencatatan pelanggaran.</div>@endforelse</div></section>
</div>
@else
<div class="page-wrap"><section class="panel module-panel"><div class="panel-title"><div><h1>{{ $title }}</h1><p>{{ $description }}</p></div><div class="module-actions"><a class="soft-action" href="{{ route('dashboard') }}"><span class="material-symbols-outlined">arrow_back</span>Dashboard</a></div></div><div class="module-table">@forelse($rows as $row)@if($module === 'reports')<div class="module-row"><strong>{{ $row->student?->name ?? 'Siswa tidak ditemukan' }}</strong><span>{{ $row->violationType?->name ?? 'Pelanggaran' }}</span><span>{{ $row->occurred_at?->format('d M Y') ?? '-' }}</span></div>@elseif($module === 'agenda' || $module === 'assessments')<div class="module-row"><strong>{{ $row->student?->name ?? 'Siswa tidak ditemukan' }}</strong><span>{{ $row->topic ?? 'Sesi konseling' }}</span><span>{{ $row->scheduled_at?->format('d M Y H:i') ?? '-' }}</span></div>@else<div class="module-row"><strong>{{ $row->name }}</strong><span>{{ $row->category ?? 'Umum' }}</span><span>Aktif</span></div>@endif @empty<div class="empty-state">Belum ada data untuk modul ini.</div>@endforelse</div>@if(method_exists($rows, 'links'))<div class="pagination-wrap">{{ $rows->links() }}</div>@endif</section></div>
@endif
@endsection

@push('scripts')
<script>document.addEventListener('DOMContentLoaded',()=>{const f=document.querySelector('[data-violation-form]');if(!f)return;const s=f.querySelector('[data-student-select]'),r=f.querySelector('[data-student-name]'),p=f.querySelector('[data-student-points]'),old=f.querySelector('[data-old-points]'),nw=f.querySelector('[data-new-points]'),total=f.querySelector('[data-total-points]'),meter=f.querySelector('[data-meter]'),th=f.querySelector('[data-threshold]');const update=()=>{const o=s.options[s.selectedIndex],base=Number(o?.dataset.points||0),add=Number(f.querySelector('input[name="violation_type_id"]:checked')?.dataset.points||0),sum=base+add;r.textContent=o?.value?o.textContent.split(' — ')[0]:'Belum memilih siswa';p.textContent=base;old.textContent=base;nw.textContent=add;total.textContent=sum;th.textContent=`${sum} / 100 Poin`;meter.style.width=Math.min(sum,100)+'%'};s.addEventListener('change',update);f.querySelectorAll('input[name="violation_type_id"]').forEach(x=>x.addEventListener('change',update));f.querySelectorAll('[data-category]').forEach(b=>b.addEventListener('click',()=>{f.querySelectorAll('[data-category]').forEach(x=>x.classList.remove('active'));b.classList.add('active');f.querySelectorAll('.violation-option').forEach(x=>x.hidden=x.dataset.typeCategory!==b.dataset.category)}));f.querySelector('[data-category]')?.click();update()});</script>
@endpush
‍
