@extends('layouts.dashboard')

@section('content')
<div class="violation-page">
    <div class="violation-page-head">
        <div><span class="eyebrow">SISTEM KEDISIPLINAN TERPADU</span><h1>Input &amp; Pencatatan Pelanggaran Siswa</h1><p>Pencatatan kedisiplinan siswa dengan kalkulasi poin otomatis dan notifikasi wali kelas serta orang tua.</p></div>
        <div class="quick-status"><span><i></i> Petugas: {{ auth()->user()->name }}</span><b><span class="material-symbols-outlined">schedule</span>{{ now()->format('d M Y, H:i') }} WIB</b></div>
    </div>
    @if(session('success'))<div class="alert-success"><span class="material-symbols-outlined">check_circle</span>{{ session('success') }}</div>@endif
    @if($errors->any())<div class="alert-error"><span class="material-symbols-outlined">error</span>{{ $errors->first() }}</div>@endif
    <form method="POST" action="{{ route('dashboard.violation.store') }}" enctype="multipart/form-data">
        @csrf
        <div class="violation-layout">
            <div class="violation-form-column">
                <section class="violation-card"><div class="section-heading"><div><span class="step-number">01</span><h2>Identitas Siswa Terlapor</h2></div><small>Pencarian otomatis</small></div><div class="student-search" data-student-lookup data-endpoint="{{ route('dashboard.students.lookup') }}"><div class="student-picker"><span class="material-symbols-outlined">person_search</span><input type="search" data-student-query placeholder="Cari nama siswa atau NIS..." autocomplete="off" aria-label="Cari nama siswa atau NIS"><span class="material-symbols-outlined">search</span></div><div class="student-results" data-student-results hidden></div><input type="hidden" name="student_id" data-student-id value="{{ old('student_id') }}" required></div><div class="selected-student" data-selected-student hidden><div class="student-avatar" data-selected-initials>—</div><div><strong data-selected-name>Pilih siswa</strong><small data-selected-meta></small></div><div class="student-points"><strong data-selected-points>0</strong><span>Poin berjalan</span></div><button type="button" class="student-clear" data-student-clear aria-label="Ganti siswa"><span class="material-symbols-outlined">close</span></button></div></section>
                <section class="violation-card"><div class="section-heading"><div><span class="step-number">02</span><h2>Pilih Jenis Pelanggaran</h2></div><a href="{{ route('dashboard.module', 'settings') }}">Buku Pedoman BK</a></div><div class="violation-options">@foreach($violationTypes as $type)<label class="violation-option"><input type="radio" name="violation_type_id" value="{{ $type->id }}" required @checked(old('violation_type_id') == $type->id)><span><strong>{{ $type->name }}</strong><small>{{ $type->category }}</small></span><b>+{{ $type->point_weight }} Poin</b></label>@endforeach</div></section>
                <section class="violation-card"><div class="section-heading"><div><span class="step-number">03</span><h2>Kontekstual Kejadian</h2></div><small>Wajib diisi</small></div><div class="form-grid"><label>Waktu &amp; Tanggal Kejadian<input type="datetime-local" name="occurred_at" value="{{ old('occurred_at', now()->format('Y-m-d\\TH:i')) }}" required></label><label>Lokasi Kejadian<select name="location" required><option value="Gerbang Depan Sekolah">Gerbang Depan Sekolah</option><option value="Ruang Kelas">Ruang Kelas</option><option value="Kantin">Kantin</option><option value="Lainnya">Lainnya</option></select></label></div><label class="notes-field">Catatan Guru Piket &amp; Alasan Siswa<textarea name="notes" rows="4" required placeholder="Tuliskan kronologi kejadian...">{{ old('notes') }}</textarea></label><label class="upload-field"><span class="material-symbols-outlined">photo_camera</span><span><strong>Dokumentasi bukti (opsional)</strong><small>PNG, JPG atau PDF maksimal 5 MB</small></span><input type="file" name="evidence" accept="image/*,.pdf"></label></section>
            </div>
            <aside class="violation-side-column"><section class="summary-card"><div class="section-heading"><div><span class="material-symbols-outlined">calculate</span><h2>Kalkulasi Otomatis Poin Siswa</h2></div><small>Real-Time Sync</small></div><div class="point-summary"><div><small>Poin Lama</small><strong>—</strong></div><em>+</em><div><small>Pelanggaran Baru</small><strong>—</strong></div><em>=</em></div><div class="threshold"><div><span>Ambang Batas Peringatan BK</span><b>100 Poin</b></div><i><b></b></i><small>0 Poin (Aman) · 50 (SP1) · 75 (SP2) · 100 (Konferensi Kasus)</small></div></section><section class="summary-card action-card"><div class="section-heading"><div><span class="material-symbols-outlined">notifications_active</span><h2>Distribusi Notifikasi</h2></div></div><p>Sistem akan mengirim ringkasan data kedisiplinan setelah formulir disimpan.</p><label><input type="checkbox" name="notify_homeroom_teacher" value="1" checked><span class="material-symbols-outlined">groups</span>WhatsApp ke Wali Kelas</label><label><input type="checkbox" name="notify_guardian" value="1" checked><span class="material-symbols-outlined">family_home</span>Notifikasi Orang Tua/Wali</label><button class="primary-action submit-violation" type="submit"><span class="material-symbols-outlined">save</span>Simpan &amp; Kirim Notifikasi</button><button class="reset-action" type="reset">Reset Formulir</button></section></aside>
        </div>
    </form>
    <section class="violation-card recent-violations"><div class="section-heading"><div><span class="material-symbols-outlined">history</span><h2>Pencatatan Kedisiplinan Terakhir</h2></div><a href="{{ route('dashboard.module', 'reports') }}">Lihat laporan lengkap →</a></div><div class="recent-table"><div class="recent-row recent-head"><span>WAKTU</span><span>NAMA SISWA</span><span>JENIS PELANGGARAN</span><span>POIN</span><span>STATUS</span></div>@forelse($rows->take(5) as $row)<div class="recent-row"><span>{{ $row->occurred_at?->format('H:i') }} WIB</span><strong>{{ $row->student?->name ?? '-' }}</strong><span>{{ $row->violationType?->name ?? '-' }}</span><b>+{{ $row->point_snapshot }}</b><em>Terkirim</em></div>@empty<div class="empty-state">Belum ada pencatatan pelanggaran.</div>@endforelse</div></section>
</div>
@endsection
